### ISSUE TITLE
Add Noroff Logo as alt text to logo image and restore path

### ISSUE THREAD

**Issue by runeunhjem** [NoroffFEU/agency.noroff.dev#662]
Add Noroff Logo as alt text to logo image

**Comment by runeunhjem** [comment]
Path is fixed, so just add the alt text

**Comment by haiderf7** [comment]
Added alt text to noroff logo on src/js/ui/header/index.js

**Comment by haiderf7** [comment]
Should now be done on pr:[Added alt text to noroff logo on src/js/ui/header/index.js by haiderf7 · Pull Request #673 · NoroffFEU/agency.noroff.dev (github.com)](https://github.com/NoroffFEU/agency.noroff.dev/pull/673)

**Comment by haiderf7** [comment]
Was some conflicts on the PR because og the prettier update, i tried to run git checkout main -- .prettierrc.json but that didnt resolve the conflict, i spoke with QA and  the QA will resolve the manually this time.
